### PR TITLE
Fix specify username password

### PR DESCRIPTION
**Pull request by cpina**
This should fix https://github.com/subdownloader/subdownloader/issues/48

### CODE REVIEW

**Comment by amoe** [comment]
Hi, thanks for your work @cpina.

Here's the behaviour I'm seeing with this branch:

* On the main UI view, "Log in" button greyed out, and the string `status` next to it, with nothing else present.
* On the `Main` menu, `Log in` and `Log out` are both greyed out.
* `Main` > `Providers...` doesn't do anything.
* `Settings` > `Configure Subdownloader...` causes a crash `'NoneType' object has no attribute 'get_path'`.
* Selecting a directory doesn't scan it for videos, instead the "How To Use SubDownloader" text remains.

However all of these behaviours are also happening with the `master` branch that `fix-specify-username-password` was based on, so I don't think any of them are caused by your changes.  There is some delay at startup that indicates that SubDownloader is at least trying to authenticate to opensubtitles, but I have no way to check whether it succeeded or not.

Sorry I couldn't be of more help here.

Cheers!
Dave

**Comment by cpina** [comment]
Thanks Dave - yes there are a few things to improve.

I'm more "worried" to know if subdownloader is maintained or not before I put too much effort (yes, I can fork and do it for me but at least I can download subtitles now :-). Is there any maintainer?

**Comment by sergiomb2** [comment]
I applied yours commit in my branch here: https://github.com/sergiomb2/subdownloader/ , please test master branch

**Comment by sergiomb2** [comment]
Merged https://github.com/subdownloader/subdownloader/commit/8d48c414818e0c5cbe8afe354658e52306284a82 and 241af54521853d99eb0a92a96854620041ef9a6b

**Comment by madebr** [comment]
I think it's safe to close this one?
Please comment if I'm wrong.

**Pull request closed without merging**
