### PR TITLE
Refactoring subdownloader

### PR DESCRIPTION
**Pull request by madebr**
Hey,

At the moment, the code of subdownloader is a mess so major refactoring is needed.
This is a first step in that direction.
I will try to keep the program working, but occasional breakage may occur.
In case of breakage or comments, feel free to comment or open an issue.

- I would like to separate the backend and frontend of subdownloader.
  That way, python developers are able to import our library and
  update their media library using some api
  * I put the library in the `subdownloader` directory
  * The frontend is put in the `subdownloader/client` directory
- Additionally, the backend should be split in general logic and provider specific stuff.
  The target is to support multiple subtitle providers.
  All logic dedicated to specific providers are to be put in the `subdownloader/provider` directory. So future effort will be put in extract specific opensubtitles.org from the backend and guis.
- I renamed `run.py` to `subdownloader.py`.

Please comment.

@sergiomb2 @capiscuas

### CODE REVIEW

**Comment by sergiomb2** [comment]
I like the idea , I will test soon I have some free time , maybe next weekend . 
I also add some new commits you may check it out in my repo, I do a lot of git push --force , so they may change without notice 
One question in ChangeLog you add https://github.com/madebr/subdownloader/commits/master , shouldn't we use https://github.com/subdownloader/subdownloader/ as official page ? 

Thanks

**Comment by madebr** [comment]
Oversight on my part. I will fix it.

**Comment by sergiomb2** [comment]
should I make the setup.py for setuptools ?

**Comment by madebr** [comment]
Feel free to. When time permits, I'm working on refactoring.

**Comment by sergiomb2** [comment]
Cool ! , you added my 3 new commits, please let me know when I should start testing this new code  . 
BTW should we tag master code with v2.0.19 ? to have a point of comparison between what we have working before and what we have working in new version ...

**Comment by madebr** [comment]
I incremented the version in the source code too early.
The next release will be 2.0.19, and will be tagged.

The plan is to create that release once milestone 2.0.19 is finished.

Because some code is still a mystery for me and I feel uncomfortable supporting it for a release, I got sidetracked by refactoring the code.
Meanwhile, I hope to meet milestone 2.0.19.

**Comment by sergiomb2** [comment]
> I incremented the version in the source code too early.

hum ,  I meant tag https://github.com/subdownloader/subdownloader/commits/master commit 2cb0ffbbdc83e6822cfcf288cdf268b21604ed47 it already have APP_VERSION = "2.0.19" , this refactoring should be 2.1.x or 3.0.x . 

Tag it , doesn't mean that we must support it , it just to compare what is working in one version and in other . 2.0.19

How you want call this milestone 2.1 or 3.0 ? any way doesn't even start in my Fedora 24 have you test it ? how we may see it work ?

**Comment by madebr** [comment]
I see your reasoning.

What about this?
- just merge this PR (after I feel comfortable with it)
- tag some known working commit v2.0.19
- don't create a release 2.0.19
- fix all errors (currently in milestone 2.0.19), some refactoring allowed
- current milestones 2.0.20 and 2.0.21 will get another name

**Comment by sergiomb2** [comment]
I mean tag before merge this PR, I see in this PR many new things like introduction of langdetect , also think with this PR we should bump a major version to 2.1 or even 3 . 

> I am also running on a fedora 24 box. It works on my machine

./subdownloader.py 
```
Traceback (most recent call last):
  File "./subdownloader.py", line 12, in <module>
    install_i18n_early()
  File "/home/sergio/fedora-scm/subdownloader/subdownloader.github/subdownloader/client/configuration.py", line 24, in install_i18n_early
    domain='subdownloader', localedir=get_i18n_path(), languages=[lc], fallback=True).install()
  File "/usr/lib64/python2.7/gettext.py", line 543, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/usr/lib64/python2.7/gettext.py", line 515, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib64/python2.7/gettext.py", line 207, in _expand_lang
    locale = normalize(locale)
  File "/usr/lib64/python2.7/locale.py", line 384, in normalize
    code = localename.translate(_ascii_lower_map)
AttributeError: 'NoneType' object has no attribute 'translate'


```

**Comment by sergiomb2** [comment]
OK , found the problem and is working with: https://github.com/sergiomb2/subdownloader/commit/bd91dab7655d14a94e36d35462d9ea386042ef4e 

OK and if you think that we don't have much changes that new version is equal of previous , I accept your plan , but anyway I suggest a new numeration for example 2.1.0 but if you want call it 2.0.19 also fine to me, I'm just expressing my ideas, nothing important .

**Comment by madebr** [comment]
You're right. My numbering was off. Your suggestion looks fine.
New understanding:
- tag the commit you were referring to as 2.0.19 (2cb0ffbbdc83e6822cfcf288cdf268b21604ed47)
- merge this PR and once we feel comfortable with the code base, tag it 2.1.0
- Start with 3.0.0 only once we add new features.

Thanks for your commit sergiomb2@bd91dab7655d14a94e36d35462d9ea386042ef4e, I will incorporate it.

**Comment by madebr** [comment]
Can you test this PR?
Then, I can merge it.
From then on, you can open issues in github to report problems.

**Comment by madebr** [comment]
Regarding your langdetect problem, I installed it using pip/pip3.

**Comment by sergiomb2** [comment]
> You're right. My numbering was off. Your suggestion looks fine.
> New understanding:
> 
> - tag the commit you were referring to as 2.0.19 (2cb0ffb)

yes , please
> - merge this PR and once we feel comfortable with the code base, tag it 2.1.0

yes , please 
> - Start with 3.0.0 only once we add new features.

and also agree with this.

**Comment by sergiomb2** [comment]
I had done some tests, also had one big test that crash on version 2.0.19 but no crash now, also test translations and system locale looks that all are working well .
Thanks. 
Notes: 
why not add 93d634e195bfbdf0bf2587dec38f4f563d5527e6

**Comment by madebr** [comment]
Thanks for testing. I'll merge this PR as soon as I can.
I didn't include that commit (yet) because I'm not sure yet how to handle things:
- I'm thinking about using git submodule and
- langdetect is currently only used in Language.from_file. That function is not used anywhere.

Currently I'm in favor for the git submodule approach. See madebr/subdownloader#4
(I'm using the issue tracker on my repo as a todo list for myself. The tracker on this repo is for user visible problems)

**Comment by sergiomb2** [comment]
in reply if "langdetect is currently only used in Language.from_file. That function is not used anywhere."
so maybe we can drop all ...
As you want keep generated file to allow us run it from local repo , I suggest add modules that might not be in system , I don't think we should use git submodule, because these modules are not part of the code ... 
I'm thinking in make an script to check if we have modules that we need on system , and maybe generate to generated files , etc , but now an in a hurry I haven't time to be more specific .
I'm packager of subdownloader in Fedora I'd like update to a new version ... , but I need code tagged (to be more beautiful) 
Thanks.

**Comment by madebr** [comment]
- git submodule is not that hard, just init and sync
- Releases must of course copy the submodules in the source archive
- Your spec file can than just use that archive and be done with it
- It's a bit too early to push an update to Fedora. I still have to comb through a lot of code.

**Comment by sergiomb2** [comment]
if you tag the commit you were referring to as 2.0.19 (2cb0ffb) I package that to Fedora, doesn't get worse . 
BTW I can do the tag if you invite me to the project , don't know if is a good idea. 

> Releases must of course copy the submodules in the source archive

here is one problem when you tag one commit , archive doesn't include submodules 

>  Your spec file can than just use that archive and be done with it

I know , but I thin is more beautiful use one tag instead one commit  

> It's a bit too early to push an update to Fedora. I still have to comb through a lot of code.

Don't worry with that , people deserve a better version that they have know (which is 2.10.18 with a very few bug fixes) as I already wrote , doesn't get worse 😄 . 


Thanks

**Comment by madebr** [comment]
- There won't be a 2.0.19 release. The gui still crashes at shutdown and thus may have many problems yet to be identified. Please don't release a premature version to the public. Even so, there is no hurry in a fast release. 2.0.18 will have to do in the mean time. People may get a distaste if it does not work out.
- You don't package from git but from a source tarball. That tarball will not contain git submodules. (A script will be written in the distribution dir to create that archive)
- When I tag a commit, the archive created by github will not include submodules. But, github allows me to attach extra files to a release. See [here](https://github.com/blog/1547-release-your-software). Just use that.

I will now continue to refactor the code. A release will be done. When it is finished.

**Comment by sergiomb2** [comment]
OK don't worry please, take a look here : https://src.fedoraproject.org/cgit/rpms/subdownloader.git/tree/

I know that 2.0.19 will not be released  what we call tag  2.0.19 **have many bug fixes since** 2.0.18 , anything is better that we have now . Prior to my efforts, not even the common subs download worked.

**Comment by sergiomb2** [comment]
> 
>         tag the commit you were referring to as 2.0.19 (2cb0ffb)
> 
> yes , please

Hi, if not much trouble, may we have this tag please ? 
For a lots of reasons I want update subdownloader.spec with 
Source0:    https://github.com/subdownloader/%{name}/releases/tag/v%{version}/%{name}-%{version}.tar.gz

**Comment by madebr** [comment]
No, I won't push that tag because I don't want a 2.0.19 release to appear in the Releases tab.
You can always change your Source0 with a specific commit as described in this [Fedora packaging guideline wiki page](https://fedoraproject.org/wiki/Packaging:SourceURL?rd=Packaging/SourceURL#Commit_Revision) (Commit Revision)

Use this url:
https://github.com/subdownloader/subdownloader/archive/2cb0ffbbdc83e6822cfcf288cdf268b21604ed47.tar.gz#/subdownloader-2cb0ffbbdc83e6822cfcf288cdf268b21604ed47.tar.gz

It might be useful in the future to (test) package certain commits instead of only allowing releases.

Add some logic in your spec about using git commits for testing and releases for releases.

**Comment by sergiomb2** [comment]
OK , no worries , I don't understand why you "don't want a 2.0.19 release to appear in the Releases tab" , is the best that we have at this moment, but no worries. Thanks for the quick reply .

**Pull request merged**
